import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbars from "./components/Navbars/Navbars";
import { LanguageProvider } from "./context/LanguageContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <LanguageProvider>
            <Navbars />
            {children}
          </LanguageProvider>
      </body>
    </html>
  );
}
